name: with_value
description: "Simple InheritedWidget Wrapper."
version: 0.0.1

repository: https://github.com/ericwimp8/with_value

homepage: https://github.com/ericwimp8/with_value

issue_tracker: https://github.com/gskinner/with_value/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
